---
engines:
  duplication:
    enabled: true
    exclude_paths:
      - "SiphonTests/**"
      - "scripts/**"
  markdownlint:
    enabled: false
  remark-lint:
    enabled: false
exclude_paths:
  - "SUPPORTED_SITES.md"
  - "CHANGELOG.md"
  - "docs/**"
  - "SiphonTests/**"
