# SonarCloud configuration for automatic analysis
sonar.projectKey=marspater_jolly-hopper
sonar.organization=marspater

sonar.sources=Siphon,SiphonExtension_Chrome,SiphonExtension_Firefox,SiphonExtension_Safari,server,scripts
sonar.tests=SiphonTests
sonar.python.version=3.10, 3.11, 3.12, 3.13

sonar.exclusions=build/**,assets/**
