# SonarCloud configuration for automatic analysis
sonar.projectKey=marspater_jolly-hopper
sonar.organization=marspater

sonar.sources=Siphon,SiphonExtension_Chrome,SiphonExtension_Firefox,SiphonExtension_Safari,server,scripts
sonar.tests=SiphonTests

sonar.exclusions=build/**,assets/**
