sonar.projectKey=marspater_jolly-hopper
sonar.organization=marspater
sonar.projectName=jolly-hopper

# Source and Test directories
sonar.sources=Siphon,SiphonExtension_Chrome,SiphonExtension_Firefox,SiphonExtension_Safari,server,scripts
sonar.tests=SiphonTests

# Language specific settings
sonar.swift.project=Siphon.xcodeproj
sonar.swift.appScheme=Siphon

# Exclusions
sonar.exclusions=build/**,assets/**
