import SwiftUI

enum Language: String, CaseIterable, Identifiable {
    case english = "en"
    
    var id: String { self.rawValue }
    
    var displayName: String {
        return "English"
    }
}

class LanguageService: ObservableObject {
    @AppStorage("selectedLanguage") var selectedLanguage: Language = .english
    @AppStorage("isFirstLaunch_v3") var isFirstLaunch: Bool = true
    
    func s(_ key: String) -> String {
        return translations[key] ?? key
    }
    
    private let translations: [String: String] = [
        "home": "Home",
        "downloading": "Downloading",
        "queued": "Queued",
        "completed": "Completed",
        "history": "History",
        "keyring": "Keyring",
        "settings": "Settings",
        "new_download": "Add New Download",
        "url_placeholder": "Download video from YouTube and thousands of sites",
        "stat_downloading": "Downloading",
        "stat_queued": "Queued",
        "stat_completed": "Completed",
        "stat_failed": "Failed",
        "empty_failed": "No failed downloads",
        "download_failed_error": "Download failed: %@",
        "subtitle_download_failed": "Subtitle download failed: %@",
        "too_many_requests": "Too many requests (429). Please select a browser in Settings > Advanced.",
        "preferences": "Preferences",
        "general": "General",
        "download": "Download",
        "advanced": "Advanced",
        "about": "About",
        "theme": "Theme",
        "system": "System",
        "light": "Light",
        "dark": "Dark",
        "language": "Language",
        "save_folder": "Default Save Folder",
        "select": "Select...",
        "updates": "Updates",
        "check_updates": "Check for Updates",
        "update_now": "Update Now",
        "format_settings": "Format Settings",
        "file_type": "Default File Type",
        "video_quality": "Default Video Quality",
        "embed_options": "Embedding Options",
        "embed_thumbnail": "Embed thumbnail",
        "embed_metadata": "Embed metadata",
        "concurrent_downloads": "Concurrent Downloads",
        "max": "Maximum",
        "sponsorblock_desc": "SponsorBlock automatically skips sponsor segments in YouTube videos.",
        "ytdlp_update": "yt-dlp Update",
        "update_complete": "✅ Update completed!",
        "update_error": "❌ Error:",
        "downloading_ytdlp": "Downloading...",
        "version": "Version",
        "special_thanks": "Special Thanks",
        "credits": "Credits",
        "license": "License",
        "license_desc": "This software is free software. You can modify and redistribute it.",
        "supported_sites": "Supported Sites",
        "other": "Other",
        "empty_downloading": "No downloading videos at the moment",
        "empty_queued": "No queued videos",
        "empty_completed": "No completed downloads",
        "video": "Video",
        "audio": "Audio",
        "default_video_resolution": "Default Video Resolution",
        "sponsorblock": "SponsorBlock",
        "app_updates": "App Updates",
        "app_up_to_date": "App is up to date",
        "downloading_update": "Downloading update...",
        "installing_update": "Installing update and restarting...",
        "update_failed": "Update failed!",
        "restart_to_install": "Restart and Install",
        "update_available_title": "New Update Available!",
        "update_available_message": "A new version of VeloX Pro (v%@) is ready. Would you like to download it now?",
        "later": "Later",
        "whats_new_title": "VeloX Pro v4.0.0 - What's New? 🚀",
        "whats_new_message": "✨ New Features:\n• Cloudflare & Anti-Bot Bypasses: Seamlessly download from challenged sites like BoyfriendTV and JustTheGays.\n• macOS 27 Compatibility: Full support and optimization for the upcoming macOS 27 SDK.\n• Menu Bar App: Manage your downloads directly from the menu bar.\n• Chrome & Firefox Extension: Start downloads with one click from your browser.\n• Notification Support: Get notified instantly when downloads are finished.\n• Auto-launch: VeloX Pro is ready when your Mac starts.\n\n🔧 Other Important Changes:\n• Stability & Security: Secure handling and automated cleanup of temporary cookie files.\n• UI Improvements: Optimized home view layout and full-screen experience for large displays.",
        "star_github": "Star on GitHub",
        "latest": "Latest",
        "original_project": "Original Project",
        "view_license": "View License",
        "app_desc": "A modern macOS application that allows you to download videos from YouTube and thousands of sites.",
        "extra_settings": "Extra Settings",
        "video_url": "Video / Playlist URL",
        "url_hint": "YouTube, Instagram, X (Twitter) video or playlist link...",
        "no_subtitles": "No subtitles found",
        "additional_arguments": "Additional Arguments (Command Line)",
        "additional_arguments_hint": "e.g. --limit-rate 5M --restrict-filenames",
        "additional_arguments_help": "Check the [official documentation](https://github.com/yt-dlp/yt-dlp#usage-and-options) for all available commands.",
        "paste_from_clipboard": "Paste from Clipboard",
        "fetch_info": "Get Video Information",
        "quality": "Quality",
        "custom_filename_hint": "Custom Filename (optional)",
        "subtitles": "Subtitles",
        "download_subtitles": "Download Subtitles",
        "subtitles_selected": "%d languages selected",
        "languages": "Languages:",
        "macos_port": "macOS Port",
        "video_downloading": "Video Downloading",
        "embed_video": "Embed in video",
        "embedded_data": "Embedded Data",
        "metadata_desc": "Embed metadata (title, artist, etc.)",
        "split_chapters": "Split chapters",
        "sponsorblock_hint": "SponsorBlock (skip sponsors)",
        "cancel": "Cancel",
        "download_btn": "Download",
        "clear_history": "Clear History",
        "history_empty": "Download history is empty",
        "history_desc": "Completed downloads will appear here",
        "search_history": "Search history...",
        "play": "Play",
        "redownload": "Re-download",
        "copy_url": "Copy URL",
        "add_new": "Add New",
        "keyring_empty": "No credentials",
        "keyring_desc": "Add credentials to access password protected content",
        "add_credential": "Add Credential",
        "new_credential": "New Credential",
        "edit_credential": "Edit Credential",
        "name_hint": "Name (e.g. YouTube Premium)",
        "name": "Name",
        "username": "Username",
        "password": "Password",
        "save": "Save",
        "fetching": "Fetching Information",
        "processing": "Processing",
        "failed": "Failed",
        "paused": "Paused",
        "stop_all": "Stop All",
        "finder": "Show in Finder",
        "retry": "Retry / Resume",
        "stop": "Stop",
        "log": "Show Log",
        "remove": "Remove",
        "download_log": "Download Log",
        "close": "Close",
        "no_log": "No log yet...",
        "codec": "Codec",
        "auto_h264": "Auto (H.264)",
        "codec_warning": "Note: For resolutions above 1080p, please select AV1 or VP9 codec.",
        "support_btn": "Support VeloX Pro",
        "clear": "Clear",
        "format": "Format",
        "browser_cookies": "Login Source (Cookies)",
        "none": "None",
        "browser_hint": "Please select a browser where you have previously logged in with your YouTube account. macOS may ask for keychain access on first use; select 'Always Allow' to permanently authorize this.",
        "fix_signin_error": "Fix in Settings",
        "safari_warning": "Note: For Safari cookies, you must grant 'Full Disk Access' to VeloX Pro in System Settings > Privacy & Security. Using a browser other than Safari (Chrome, Brave, etc.) will be much easier.",
        "open_system_settings": "Open System Settings",
        "video_codec": "Video Codec",
        "audio_codec": "Audio Codec",
        "codec_auto": "Auto (Best Available)",
        "codec_settings": "Codec Settings",
        "reset_to_defaults": "Reset to Defaults",
        "download_presets": "Download Presets",
        "preset_best_quality": "Best Quality",
        "preset_max_compatibility": "Max Compatibility",
        "preset_smallest_size": "Smallest Size",
        "preset_audio_only": "Audio Only",
        "preset_best_quality_desc": "AV1 + Opus, Highest quality",
        "preset_max_compatibility_desc": "H.264 + AAC, Works on all devices",
        "preset_smallest_size_desc": "AV1 720p, Smallest file size",
        "preset_audio_only_desc": "Download audio only (M4A)",
        "apply_preset": "Apply Preset",
        "preferred_video_codec": "Preferred Video Codec",
        "preferred_audio_codec": "Preferred Audio Codec",
        "codec_fallback_note": "Note: If selected codec is unavailable, the best alternative will be selected automatically.",
        "res_best": "Best",
        "res_worst": "Worst",
        "subtitle_format": "Subtitle Format",
        "file_exists_title": "File Already Exists",
        "file_exists_message": "A file with this name already exists. What would you like to do?",
        "overwrite": "Overwrite",
        "add_number": "Append number to filename",
        "h264_resolution_warning": "H.264 codec does not support resolutions above 1080p. Please select VP9 or AV1 codec or use a different preset.",
        "subtitle_output": "Subtitle Output",
        "subtitle_external": "External File",
        "subtitle_embedded": "Embedded",
        "h264_preset_info": "H.264 codec selected. Maximum quality is limited to 1080p.",
        "download_completed_title": "Download Completed",
        "download_completed_body": "%@ downloaded successfully.",
        "download_failed_title": "Download Error",
        "download_failed_body": "An error occurred while downloading %@.",
        "launch_at_login": "Launch at login",
        "start_in_background": "Start in background",
        "start_in_background_desc": "On login, only the menu bar icon will be shown, not in Dock",
        "quit": "Quit",
        "open_macabolic": "Open VeloX Pro",
        "show_main_window": "Show Main Window",
        "preset": "Preset",
        "standard": "Standard",
        "custom": "Custom",
        "notifications": "Notifications",
        "show_menubar_icon": "Show Menu Bar Icon",
        "first_sponsor": "First Sponsor",
        "test_notification": "Send Test Notification"
    ]
}
