name: Xcode - Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Test (Debug)
        run: |
          xcodebuild test \
            -project Siphon.xcodeproj \
            -scheme Siphon \
            -destination 'platform=macOS' \
            -configuration Debug \
            MACOSX_DEPLOYMENT_TARGET=14.0 \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Test (Release)
        run: |
          xcodebuild test \
            -project Siphon.xcodeproj \
            -scheme Siphon \
            -destination 'platform=macOS' \
            -configuration Release \
            MACOSX_DEPLOYMENT_TARGET=14.0 \
            ENABLE_TESTABILITY=YES \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
