import SwiftUI

enum Language: String, CaseIterable, Identifiable {
    case english = "en"
    
    var id: String { self.rawValue }
    
    var displayName: String {
        return "English"
    }
}

@MainActor
class LanguageService: ObservableObject {
    public static let shared = LanguageService()
    @AppStorage("selectedLanguage") var selectedLanguage: Language = .english
    
    nonisolated func s(_ key: String) -> String {
        if let translated = translations[key] {
            return translated
        }
        return key.replacingOccurrences(of: "_", with: " ").capitalized
    }
    
    private let translations: [String: String] = [
        "legal_disclaimer": "Legal Disclaimer",
        "about_app": "About Siphon",
        "couldnt_download": "Couldn't download",
        "youtube_auth_required": "YouTube requires authentication",
        "login_required_desc": "Sign in or browser cookies required",
        "anti_bot_desc": "Website anti-bot challenge blocked the request",
        "drm_protected_desc": "Media is protected by DRM encryption",
        "video_unavailable_desc": "Video is private, removed, or unavailable",
        "disk_full_desc": "No space left on destination disk",
        "permission_denied_desc": "Permission denied saving to destination",
        "network_timeout_desc": "Network connection timed out",
        "unsupported_url_desc": "Unsupported URL or unrecognized host",
        "generic_error_desc": "An unexpected error occurred",
        "details": "Details",
        "hide_details": "Hide Details",
        "copy_error": "Copy Error",
        "more_actions": "More Actions",
        "pause": "Pause",
        "resume": "Resume",
        "move_up": "Move Up",
        "move_down": "Move Down",
        "move_to_top": "Move to Top",
        "move_to_bottom": "Move to Bottom",
        "change_folder": "Change Folder in Settings",
        "show_in_finder": "Reveal in Finder",
        "home": "Home",
        "downloading": "Downloading",
        "queued": "Queued",
        "completed": "Completed",
        "history": "History",
        "keyring": "Keyring",
        "settings": "Settings",
        "new_download": "Add New Download",
        "url_placeholder": "Download video from YouTube and thousands of sites",
        "stat_downloading": "Downloading",
        "stat_queued": "Queued",
        "stat_completed": "Completed",
        "stat_failed": "Failed",
        "video_downloader": "Video Downloader",
        "ready_to_download": "Ready to download.",
        "ready_to_download_subtitle": "Paste a link, drop a URL or add from your clipboard. Siphon handles the rest.",
        "more_videos_calmer_internet": "More videos.\nA calmer internet.",
        "drop_url_here": "Drop a URL here",
        "or_paste_clipboard": "or paste from your clipboard",
        "recent_downloads": "Recent downloads",
        "see_all": "See All",
        "play_videos_your_way": "Play videos.\nYour way.",
        "built_for_open_internet": "Built for a more open internet.",
        "status_active": "Active",
        "show_downloads_hint": "Show %@ downloads",
        "no_recent_downloads": "No downloads yet",
        "no_recent_downloads_sub": "Downloads will appear here once you paste or drop a link.",
        "advanced_options": "Advanced Options",
        "empty_failed": "No failed downloads",
        "empty_failed_detail": "Downloads that need attention or a retry will appear here.",
        "download_failed_error": "Download failed: %@",
        "subtitle_download_failed": "Subtitle download failed: %@",
        "download_stopped_title": "Download Stopped",
        "download_stopped_body": "Download of '%@' was stopped.",
        "too_many_requests": "Too many requests (429). Please select a browser in Settings > Advanced.",
        "ytdlp_not_found": "yt-dlp executable not found. Please download dependencies in Settings > Advanced.",
        "parse_error": "Failed to parse video information. The website structure may have changed.",
        "cloudflare_blocked": "Blocked by anti-bot protection. Siphon could not complete the browser challenge automatically.",
        "login_required": "This video requires signing in. Please configure browser cookies in Settings > Advanced > Browser Cookies.",
        "drm_protected": "This video is DRM-protected and cannot be downloaded.",
        "video_unavailable": "This video is unavailable, private, or has been removed.",
        "disk_full": "Download failed: Not enough free disk space on the target volume.",
        "permission_denied": "Download failed: Permission denied when saving file. Please check folder permissions.",
        "unsupported_url": "Unsupported URL format or unrecognized video host.",
        "ffmpeg_error": "FFmpeg media processing failed. Please verify dependencies in Settings.",
        "network_timeout": "Network connection timed out. Please check your internet connection and retry.",
        "preferences": "Preferences",
        "general": "General",
        "download": "Download",
        "advanced": "Advanced",
        "about": "About",
        "theme": "Theme",
        "appearance": "Appearance",
        "system": "System",
        "light": "Light",
        "dark": "Dark",
        "language": "Language",
        "save_folder": "Default Save Folder",
        "reset_save_folder": "Reset to default Downloads folder",
        "select": "Choose Folder",
        "choose_folder": "Choose Folder",
        "updates": "Updates",
        "check_updates": "Check for Updates",
        "update_now": "Update Now",
        "format_settings": "Format Settings",
        "file_type": "Default File Type",
        "video_quality": "Default Video Quality",
        "embed_options": "Embedding Options",
        "embed_thumbnail": "Embed thumbnail",
        "embed_metadata": "Embed metadata",
        "concurrent_downloads": "Concurrent Downloads",
        "max": "Maximum",
        "sponsorblock_desc": "SponsorBlock automatically skips sponsor segments in YouTube videos.",
        "ytdlp_update": "yt-dlp Update",
        "update_complete": "Update completed",
        "update_error": "Error:",
        "downloading_ytdlp": "Downloading...",
        "version": "Version",
        "special_thanks": "Special Thanks",
        "credits": "Credits",
        "maintainer": "Maintainer",
        "license": "License",
        "license_desc": "This software is free software. You can modify and redistribute it.",
        "supported_sites": "Supported Sites",
        "other": "Other",
        "empty_downloading": "No downloading videos at the moment",
        "empty_downloading_detail": "Active transfers will appear here as soon as a download starts.",
        "empty_queued": "No queued videos",
        "empty_queued_detail": "Downloads waiting for an available slot will appear here.",
        "empty_completed": "No completed downloads",
        "empty_completed_detail": "Finished downloads will stay here in your history.",
        "video": "Video",
        "audio": "Audio",
        "default_video_resolution": "Default Video Resolution",
        "sponsorblock": "SponsorBlock",
        "app_updates": "App Updates",
        "app_up_to_date": "App is up to date",
        "downloading_update": "Downloading update...",
        "installing_update": "Installing update and restarting...",
        "update_failed": "Update failed",
        "restart_to_install": "Restart and Install",
        "update_available_title": "Update Available",
        "update_available_message": "A new version of Siphon (v%@) is ready. Would you like to download it now?",
        "later": "Later",
        "whats_new_title": "What's New in Siphon",
        "whats_new_subtitle": "Discover the latest enhancements, improvements, and fixes in this release.",
        "whats_new_title_format": "What's New in Siphon v%@",
        "whats_new_message": "✨ Siphon v5.3.0 Highlights:\n• Architecture Modularization: Dedicated DownloadQueue, DownloadExecutor, DownloadHistoryStore, and ProcessLifecycleState.\n• Sandboxed Cookie Lifecycle: SecureCookieFile with 0o600 permissions, scoped automatic cleanup, and startup orphan sweep.\n• Swift-Owned Auto-Updater: Native DMG staging, atomic backup/rollback, and dual-mode Developer ID / ad-hoc signature verification.\n• Sanitized Log Export: Async log snapshot export with automatic credential, cookie, and token redaction.\n• Swift 6 Concurrency: Actor-isolated BrowserUtils and CookieManager eliminating concurrency races.",
        "continue": "Continue",
        "get_started": "Get Started",
        "view_on_github": "Release Notes",
        "star_github": "Star on GitHub",
        "latest": "Latest",
        "original_project": "Original Project",
        "view_license": "View License",
        "app_desc": "A modern macOS application that allows you to download videos from YouTube and thousands of sites.",
        "extra_settings": "Extra Settings",
        "video_url": "Video / Playlist URL",
        "url_hint": "YouTube, Instagram, X (Twitter) video or playlist link...",
        "no_subtitles": "No subtitles found",
        "additional_arguments": "Additional Arguments (Command Line)",
        "additional_arguments_hint": "e.g. --limit-rate 5M --restrict-filenames",
        "additional_arguments_help": "Check the [official documentation](https://github.com/yt-dlp/yt-dlp#usage-and-options) for all available commands.",
        "paste_from_clipboard": "Paste from Clipboard",
        "paste": "Paste",
        "fetch": "Fetch",
        "fetch_info": "Get Video Information",
        "format_and_quality": "Format & Quality",
        "quality": "Quality",
        "custom_filename": "Custom Filename",
        "custom_filename_hint": "Custom Filename (optional)",
        "subtitles": "Subtitles",
        "download_subtitles": "Download Subtitles",
        "subtitles_selected": "%d languages selected",
        "languages": "Languages:",
        "macos_port": "macOS Port",
        "video_downloading": "Video Downloading",
        "embed_video": "Embed in video",
        "embedded_data": "Embedded Data",
        "metadata_desc": "Embed metadata (title, artist, etc.)",
        "split_chapters": "Split chapters",
        "sponsorblock_hint": "SponsorBlock (skip sponsors)",
        "cancel": "Cancel",
        "download_btn": "Download",
        "clear_history": "Clear History",
        "clear_history_help": "Clear download history list (downloaded files will not be deleted)",
        "history_empty": "Download history is empty",
        "history_desc": "Completed downloads will appear here",
        "search_history": "Search history...",
        "play": "Play",
        "redownload": "Re-download",
        "copy_url": "Copy URL",
        "add_new": "Add New",
        "keyring_empty": "No credentials",
        "keyring_desc": "Add credentials to access password protected content",
        "add_credential": "Add Credential",
        "new_credential": "New Credential",
        "edit_credential": "Edit Credential",
        "name_hint": "Name (e.g. YouTube Premium)",
        "name": "Name",
        "username": "Username",
        "password": "Password",
        "save": "Save",
        "fetching": "Fetching Information",
        "processing": "Processing",
        "failed": "Failed",
        "paused": "Paused",
        "stop_all": "Stop All",
        "finder": "Reveal in Finder",
        "retry": "Retry / Resume",
        "stop": "Stop",
        "log": "Show Log",
        "remove": "Remove",
        "remove_from_history": "Remove from history (keep downloaded file)",
        "download_log": "Download Log",
        "close": "Close",
        "no_log": "No log yet...",
        "codec": "Codec",
        "auto_h264": "Auto (H.264)",
        "codec_warning": "Note: For resolutions above 1080p, please select AV1 or VP9 codec.",
        "support_btn": "Support Siphon",
        "clear": "Clear",
        "format": "Format",
        "browser_cookies": "Login Source (Cookies)",
        "none": "None",
        "browser_hint": "Select your browser to access login session cookies for protected or age-restricted videos.",
        "helium_extension_supported": "Helium Browser Extension Ready",
        "helium_hint": "Siphon reads cookies from your active Helium profile using Helium Storage Key in macOS Keychain. Allow access when prompted. The Siphon Extension can also forward the current page session.",
        "fix_signin_error": "Fix in Settings",
        "safari_warning": "Safari cookie access could not be confirmed for this running copy of Siphon. Downloads will still attempt to read cookies. If macOS denies access, enable this copy in System Settings > Privacy & Security > Full Disk Access.",
        "safari_fda_required": "Safari cookies require Full Disk Access on macOS. Please grant Full Disk Access to Siphon in System Settings > Privacy & Security > Full Disk Access, or choose another browser in Settings > Advanced.",
        "safari_fda_restart_hint": "Note: After toggling Full Disk Access in System Settings, restart Siphon for permissions to take effect.",
        "open_system_settings": "Open System Settings",
        "check_permission": "Check Permission",
        "restart_siphon": "Restart Siphon",
        "safari_fda_granted_feedback": "Safari cookie file is readable by this copy of Siphon.",
        "safari_fda_not_detected_hint": "Safari cookie access could not be confirmed. If Full Disk Access is already enabled, check that it refers to the running copy of Siphon, then restart Siphon.",
        "video_codec": "Video Codec",
        "audio_codec": "Audio Codec",
        "post_processing": "Post-Processing",
        "hdr_dynamic_range": "HDR / Dynamic Range",
        "codec_auto": "Auto (Best Available)",
        "codec_settings": "Codec Settings",
        "reset_to_defaults": "Reset to Defaults",
        "download_presets": "Download Presets",
        "preset_best_quality": "Best Quality",
        "preset_max_compatibility": "Max Compatibility",
        "preset_smallest_size": "Smallest Size",
        "preset_audio_only": "Audio Only",
        "preset_best_quality_desc": "AV1 + Opus, Highest quality",
        "preset_max_compatibility_desc": "H.264 + AAC, Works on all devices",
        "preset_smallest_size_desc": "AV1 720p, Smallest file size",
        "preset_audio_only_desc": "Download audio only (M4A)",
        "apply_preset": "Apply Preset",
        "preferred_video_codec": "Preferred Video Codec",
        "preferred_audio_codec": "Preferred Audio Codec",
        "codec_fallback_note": "Note: If selected codec is unavailable, the best alternative will be selected automatically.",
        "res_best": "Best",
        "res_worst": "Worst",
        "subtitle_format": "Subtitle Format",
        "subtitle_auto_format": "%@ [Auto]",
        "file_exists_title": "File Already Exists",
        "file_exists_message": "A file with this name already exists. What would you like to do?",
        "overwrite": "Overwrite",
        "add_number": "Append number to filename",
        "h264_resolution_warning": "H.264 codec does not support resolutions above 1080p. Please select VP9 or AV1 codec or use a different preset.",
        "subtitle_output": "Subtitle Output",
        "subtitle_external": "External File",
        "subtitle_embedded": "Embedded",
        "h264_preset_info": "H.264 codec selected. Maximum quality is limited to 1080p.",
        "download_completed_title": "Download Completed",
        "download_completed_body": "%@ downloaded successfully.",
        "download_failed_title": "Download Error",
        "download_failed_body": "An error occurred while downloading %@.",
        "launch_at_login": "Launch at login",
        "start_in_background": "Start in background",
        "start_in_background_desc": "On login, only the menu bar icon will be shown, not in Dock",
        "quit": "Quit",
        "open_app": "Open Siphon",
        "show_main_window": "Show Main Window",
        "preset": "Preset",
        "standard": "Standard",
        "custom": "Custom",
        "custom_presets": "Custom Presets",
        "no_custom_presets": "No Custom Presets",
        "create_preset": "Create Preset",
        "new_preset": "New Preset",
        "edit_preset": "Edit Preset",
        "delete_preset": "Delete Preset",
        "preset_name": "Preset Name",
        "legal_disclaimer_title": "Legal Disclaimer",
        "legal_disclaimer_message": "Siphon is provided for personal, fair-use, and educational media downloading purposes only. Users are solely responsible for compliance with applicable copyright laws, licenses, and terms of service.",
        "ok": "OK",
        "notifications": "Notifications",
        "show_menubar_icon": "Show Menu Bar Icon",
        "first_sponsor": "First Sponsor",
        "test_notification": "Send Test Notification",
        "speed_limiter": "Speed Limiter",
        "max_download_speed": "Max Download Speed",
        "unlimited": "Unlimited",
        "speed_limiter_desc": "Throttle maximum download bandwidth to prevent network congestion.",
        "batch_import": "Batch Import",
        "batch_url_count": "%d URLs",
        "single_mode": "Single / Playlist",
        "paste_multiple_urls": "Paste Multiple URLs",
        "paste_multiple_urls_hint": "Enter one URL per line...",
        "import_file": "Import .txt / .m3u File...",
        "queue_batch": "Queue %d Downloads",
        "no_valid_urls": "No valid URLs found",
        "stream_inspector": "Stream & Codec Inspector",
        "stream_inspector_desc": "Select a specific format stream or leave as Smart Auto.",
        "auto_recommended": "Smart Auto (Recommended)",
        "custom_stream": "Custom Stream",
        "select_all": "Select All",
        "deselect_all": "Deselect All",
        "download_selected": "Download %d Selected",
        "download_new_name": "Download with new name",
        "file_exists_status": "File Exists",
        "playlist_detected": "Playlist Detected",
        "entire_playlist": "Would you like to download the entire playlist or select specific videos?",
        "load_playlist": "Load Playlist Items",
        "quick_look": "Quick Look",
        "copy_file_path": "Copy File Path",
        "copy_all_paths": "Copy All File Paths",
        "quick_look_chapters": "Quick Look Chapter",
        "play_chapters": "Play Chapter",
        "res_fallback_strict": "Strict Ceiling (≤ requested)",
        "res_fallback_allow_higher": "Allow Higher (with warning)",
        "res_fallback_policy": "Resolution Fallback Policy",
        "view_diagnostics": "View Diagnostics",
        "click_to_quick_look": "Click to Quick Look",
        "copy_log": "Copy Log",
        "copy_report": "Copy Report",
        "core_options": "Core Options",
        "optional_settings": "Optional Settings",
        "advanced_settings": "Advanced Settings",
        "advanced_badge": "ADVANCED",
        "debug_logs": "Debug Logs",
        "entries": "entries",
        "done": "Done",
        "not_detected": "Not detected",
        "runtime_and_process": "Runtime & Process",
        "media_and_color": "Media & Color (HDR)",
        "command_and_logs": "Command & Logs",
        "executed_command": "Executed Command",
        "copy_command": "Copy Command",
        "execution_log_output": "Execution Log Output",
        "search_logs": "Search logs...",
        "no_log_output": "No log output recorded.",
        "reveal_in_finder": "Reveal in Finder",
        "whats_new_badge": "WHAT'S NEW",
        "hero_enter_url": "Paste video or playlist link...",
        "hero_started_download": "Started download",
        "hero_started_downloads": "Started %d downloads",
        "hero_no_clipboard_url": "No valid URL found on clipboard",
        "hero_extracting_metadata": "Extracting video metadata...",
        "hero_invalid_url": "Please enter a valid HTTP/HTTPS URL",
        "hero_unsupported_site": "Unsupported URL or unrecognized video host",
        "hero_network_error": "Network connection error. Check your internet connection.",
        "hero_options": "Options",
        "menubar_quick_download": "Quick Download",
        "menubar_press_return": "Press ⏎ to download",
        "menubar_active_downloads": "Active Downloads",
        "menubar_no_active": "No active downloads",
        "menubar_open_siphon": "Open Siphon",
        "menubar_quit": "Quit",
        "menubar_preset": "Preset"
    ]
}
